// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ocvsjzwzjyjyfybytpld.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im9jdnNqend6anlqeWZ5Ynl0cGxkIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTE4MDM5NDgsImV4cCI6MjA2NzM3OTk0OH0.8jQQDos3ibDYMX1ui22F2K_Nd9yM7YF2EdobtGtKMC4";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});